{
    "name": "Rental Vehicles Fleet",
    "version": "1.0",
    "summary": "Управление арендой техники (скутеры, мотоциклы и др.) с ТО и офисами",
    "category": "Fleet",
    "author": "",
    # "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        # "security/security.xml",
        "views/vehicle_type_views.xml",
        "views/vehicle_models.xml",
        "views/vehicle_views.xml",
        "views/manufacturer.xml",
        # "views/maintenance_status_views.xml",
        # "views/maintenance_log_views.xml",
        "views/rental.xml",
        "views/office.xml",
        "views/tarif.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
