{
    "name": "Rental Vehicles",
    "version": "19.0.1.0",
    "summary": "Управление арендой техники (скутеры, мотоциклы и др.)",
    "category": "Fleet",
    "author": "",
    # "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        # "security/security.xml",
        "views/vehicle_type_views.xml",
        "views/vehicle_models.xml",
        "views/vehicle.xml",
        "views/manufacturer.xml",
        "views/order.xml",
        "views/office.xml",
        "views/tariff.xml",
        "views/service_type.xml",
        "views/maintenance.xml",
        "views/maintenance_plan.xml",
        "views/maintenance_due_view.xml",
        "views/payout.xml",
        "views/rental_vehicles_accessory.xml",
        "wizard/renter_photo_wizard.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
